### ISSUE TITLE
SDL2.DLL (32bit) needed on Windows

### ISSUE THREAD

**Issue by motabass** [usineur/hode#10]
After downloading from https://www.libsdl.org and adding sdl2.sll to the hode-folder fixed the crash at startup.

**Comment by usineur** [comment]
SDL2 is a well-known dependency on any platform. It's not an issue.

**Comment by lemmel** [comment]
@usineur is a bit harsh, but he is right: the problem is not the SDL. He probably prefers not to waste time on support when the work is not done.

Well to help you, some advices:
- could you build the project ? (I'm under linux, so ...)
- the program may "crash" if the game's data are not correctly provided (I'm not sure about it; don't remember)
- is there something fishy about the libraries ? (use http://dependencywalker.com/ on the binary and lib)
- could you provide more information about the "crash" ? How did you start the program (command line argument) ? and so on.

**Comment by usineur** [comment]
That's it, if you want help, the least effort is to give a complete description of the issue, a full described context, a use-case to reproduce the anomaly, etc.

Anyway, feel free to reopen if the issue is not SDL2 related. I mean, if it's not just a missing DLL from a package.

Also, please kind in mind that this repo is mainly dedicated to my PS Vita and Nintendo Switch ports. I can help for other plateforms however, but only with a full description.
